CREATE DATABASE MANEJOEMPLEADOS;
GO

USE MANEJOEMPLEADOS;

CREATE TABLE DEPARTAMENTO
(
ID_DEPARTAMENTO INT PRIMARY KEY IDENTITY (1,1),
NOMBRE_DEPARTAMENTO NVARCHAR (100) NOT NULL
);

CREATE TABLE CARGO 
(
ID_CARGO INT PRIMARY KEY IDENTITY (1,1),
NOMBRE_CARGO NVARCHAR (100) NOT NULL
);

CREATE TABLE EMPLEADO (
    ID_EMPLEADO INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_EMPLEADO NVARCHAR(20) NOT NULL,
    CEDULA_EMPLEADO NVARCHAR(100) NOT NULL,
    GENERO NVARCHAR (10),
    TELEFONO_EMPLEADO NVARCHAR(20),
    FECHA_INICIO DATE NOT NULL,
    SALARIO_EMPLEADO DECIMAL(10,2) NOT NULL,
    ESTADO BIT NOT NULL,

    ID_DEPARTAMENTO INT NOT NULL,
    ID_CARGO INT NOT NULL,

    FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO),
    FOREIGN KEY (ID_CARGO) REFERENCES CARGO (ID_CARGO)
);

