CREATE DATABASE MANEJOEMPLEADOS;
GO

USE MANEJOEMPLEADOS;

CREATE TABLE DEPARTAMENTO
(
ID_DEPARTAMENTO PRIMARY KEY IDENTITY (1,1),
NOMBRE_DEPARTAMENTO NVARCHAR (100) NOT NULL
);

CREATE TABLE CARGO 
(
ID_CARGO INT PRIMARY KEY IDENTITY (1,1),
NOMBRE_CARGO NVARCHAR (100) NOT NULL
);

CREATE TABLE EMPLEADO
(
ID INT PRIMARY KEY IDENTITY (1,1),
NOMBRE_EMPLEADO NVARCHAR (150) NOT NULL, 
ID_DEPARTAMENTO INT NOT NULL, 
ID_CARGO INT NOT NULL, 
FECHA_INICIO DATE NOT NULL, 
SALARIO_EMPLEADO DECIMAL (10,2) NOT NULL, 
ESTADO BIT NOT NULL
);